### ISSUE TITLE
How to define each shape's colour

### ISSUE THREAD

**Issue by haidaoxiaofei** [HDouss/jeometry#4]
Hi Douss, I am trying to use your library to draw road networks. Mostly, it is convenient. But I encountered some issues about it.

How to define the color of each individual shape? Currently, they are all black. I notice that the axises are in red. Could customise the shapes to different colours? 

Looking forward your reply~

**Comment by haidaoxiaofei** [comment]
I found your library does not provide the interface for users to define the color of each individual shape. I added the interfaces by myself. Now it works well now.

**Comment by HDouss** [comment]
@haidaoxiaofei Absolutely. The shapes have no color by themselves. The renderer that is provided for now draws all shapes in black. You can add custom shapes that have a color property or you can implement a new renderer that does that.

**Comment by HDouss** [comment]
@haidaoxiaofei I know this is a bit old, but this issue will be addressed in v0.1. Please see #13. Final decision is to encapsulate theses attributes in `Shape` class, that will encapsulate rendering options that should be renderer-agnostic.
